language: python
python:
    - "3.9"

# command to install dependencies
# install: "pip install -r requirements.txt"
install: pip install pytest pytest-quickcheck pytest-html pytest-cov
:# command to run tests
script: python tests.py -b
